### ISSUE TITLE
Test: Integration test of the voting.

### ISSUE THREAD

**Issue by BritikovKI** [PrimeDAO/pools-contracts#121]
## Status quo

We need to check the propper work of voting via veBal.

## Acceptance criteria

- [x] We need to `deposit` some wethBal tokens like in issue #116 
- [x] After the tokens are deposited, we need to call `voteGaugeWeight` function in the controller.
- [x] After this function is called, we need to check if votes were actually successful

**Comment by bxmmm1** [comment]
This is covered by integration test on a Kovan fork in `test/integration/kovan-veBal-interactions.js`
Follow [readme](https://github.com/PrimeDAO/pools-contracts#how-to-run-integration-tests-on-kovan-fork) docs on how to run integration tests in order to test this. 

On chain TX voting tx https://kovan.etherscan.io/tx/0xb522bd4d8935a4f6fb347b1e0f2bdb73497b7e9d78c235e56df6a2f43d34555d
